events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        include /etc/nginx/domains.conf;

        # Místo, kam si Certbot odloží ověřovací soubor
        location /.well-known/acme-challenge/ {
            root /var/www/html;
        }

        # Vše ostatní zatím směřuj na frontend
        location / {
            return 301 https://$host$request_uri;
        }
    }
}
