events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name eduis.cz, www.eduis.cz, test.eduis.cz, nepomucka.eduis.cz, is.nepomucka.cz, panel.nepomucka.cz;

        # Místo, kam si Certbot odloží ověřovací soubor
        location /.well-known/acme-challenge/ {
            root /var/www/html;
        }

        # Vše ostatní zatím směřuj na frontend
        location / {
            return 301 https://$host$request_uri;
        }
    }
}
